# frozen_string_literal: true

source "https://rubygems.org"
gem 'nokogiri'
gem 'rack', '~> 2.2.4'
gem 'rspec'
gem "github-pages", "~> 227", group: :jekyll_plugins
#gem "jekyll", "~> 4.0"
# gem "rails"
